# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_cor <- function(mat) {
    .Call('_redPATH_c_cor', PACKAGE = 'redPATH', mat)
}

cp_cor <- function(mat) {
    .Call('_redPATH_cp_cor', PACKAGE = 'redPATH', mat)
}

c_run_cor <- function(mat, nwindow) {
    .Call('_redPATH_c_run_cor', PACKAGE = 'redPATH', mat, nwindow)
}

cp_run_cor <- function(mat, nwindow) {
    .Call('_redPATH_cp_run_cor', PACKAGE = 'redPATH', mat, nwindow)
}

c_run_cor_smart <- function(mat, nwindow) {
    .Call('_redPATH_c_run_cor_smart', PACKAGE = 'redPATH', mat, nwindow)
}

cp_run_cor_smart <- function(mat, nwindow) {
    .Call('_redPATH_cp_run_cor_smart', PACKAGE = 'redPATH', mat, nwindow)
}

calc_vec <- function(v1, v2) {
    .Call('_redPATH_calc_vec', PACKAGE = 'redPATH', v1, v2)
}

#' @export
KL <- function(x, logx) {
    .Call('_redPATH_KL', PACKAGE = 'redPATH', x, logx)
}

#' @export
ED2 <- function(x) {
    .Call('_redPATH_ED2', PACKAGE = 'redPATH', x)
}

